### ISSUE TITLE
Titanium Backup AVC denials cause impaired functionality 

### ISSUE THREAD

**Issue by craigacgomez** [seSuperuser/AOSP-SU-PATCH#1]
AVC denials for some SELinux policies impair Titanium Backup's functionality. For example, Titanium Backup is unable to integrate system app updates (Integrate update into ROM) which involves moving the update from /data/app to /system/app. The AVC denials prevent Titanium Backup from moving the app properly Also, restoring multiple apps using the AUTO (direct/indirect) App processing modes does not work and simply hangs up. Based on the denials shown in the logcat while trying to use Titanium Backup, I have identified the following SELinux policy changes (diff from platform/external/sepolicy after integrating AOSP-SU-PATCH).

[TitaniumBackupAVCChangeDiff.txt](https://github.com/seSuperuser/AOSP-SU-PATCH/files/43255/TitaniumBackupAVCChangeDiff.txt)

With these SELinux policy changes, Titanium Backup now works fine. I am, however, not an expert in SELinux stuff and would like you to review and validate these changes, especially to make sure they are not too open and conform to some acceptable standard

**Comment by lbdroid** [comment]
I'm a bit unclear about what is going on in this. The permissions you have added do not appear to be relevant to the purpose of writing data to the /system partition. In particular, any installed application (like titanium backup) should be running in the untrusted_app context, and then by use of su, under the su context. Not system_app.

And what is going on with the kernel:process permission? That doesn't appear to be at all relevant.

This change has the _feeling_ of being to enable some kind of hackaround for a hackaround for a bad implementation of su.

Have you communicated with the author of titanium backup to determine why it is trying to use these permissions, and maybe to come up with a better solution? As far as I can tell, su from the untrusted_app and su contexts _should_ be capable of doing anything that this program would require. I _bet_ you that he is performing an "su --context u:r:system_app:s0 -c _do something_" when just "su -c _do something_" would suffice (and work).

**Comment by craigacgomez** [comment]
That was my initial understanding as well. I am just not well versed enough with SELinux. I will talk to the author of TB to confirm.

**Comment by lbdroid** [comment]
Ok, see if you can bring them into this issue tracker. Also note that the kernel:process permission was explicitly disincluded from the su policy (by google) with "allow su { domain -kernel }:process *;" which makes me nervous about adding it back in without first understanding the full implication. Obviously it adds in something that google thinks is bad to give over even to root.

The other ones are also a bit concerning, as they authorize system_app to transition to shell and toolbox contexts directly. shell context in particular, is concerning, since shell context is authorized to transition to su context. So essentially, this could allow _any_ system_app to transition to su, possibly without even notifying the user, as long as su access is enabled for adb shell.

**Comment by lbdroid** [comment]
Any updates on this issue?

**Comment by craigacgomez** [comment]
No... Been a bit busy with work (Black Friday/Cyber Monday stuff). I will get back to this soon

**Comment by phhusson** [comment]
Just ignoring the --context option does indeed work. I'm changing su to have a blacklist of apps with quirks.

**Comment by lbdroid** [comment]
Perfect. Maybe we can turn this into a new feature, automatic context manipulation based on user lists, rather than a global blacklist.

calling userid, command, context override.
With wildcards in the command.

**Comment by phhusson** [comment]
Workaround added in https://github.com/seSuperuser/Superuser/commit/f6174c3ab34777b07d840a7ab746de1d64edab72

**Comment by lbdroid** [comment]
Lets call this fixed.
